logging:
  file:
    name: './logs/application.log'
    logback:
      rollingpolicy:
        max-file-size: 1MB
        total-size-cap: 10MB
        max-history: 30
        clean-history-on-start: true
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){faint} %clr(%-40.40logger{0}){cyan} %clr(:){faint} %clr(%m){faint}%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  level:
    com.github.yildizmy: debug
    org.springframework: warn
    org.hibernate: error
    org.springframework.security: error

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

exception:
  trace: true

app:
  security:
    jwtSecret: "A1b2C3d4E5f6G7h8I9j0K1L2M3N4O5sP"
    jwtExpirationMs: 36000000